version: "2.1"
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/
    volumes:
      - ./_config:/config
      - ./_data:/data
    ports:
      - 3000:3000
      - 8190:80
      - 4001:4001 #optional
    restart: unless-stopped
